[profile.default]
src = "contracts/src"
out = "contracts/out"
libs = ["contracts/lib"]
test = "contracts/test"
script = "contracts/script"
cache_path = "contracts/cache"

# Compiler settings
solc_version = "0.8.23"
optimizer = true
optimizer_runs = 200
via_ir = true

# Test settings
verbosity = 2

[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"
mainnet = "${MAINNET_RPC_URL}"
base-sepolia = "${BASE_SEPOLIA_RPC_URL}"
base-mainnet = "${BASE_MAINNET_RPC_URL}"
