# Foundry configuration for e2e-test contracts
# This is separate from the main contracts configuration

[profile.default]
src = "contracts/src"
out = "contracts/out"
libs = ["../contracts/lib"]
test = "contracts/test"
script = "contracts/script"

solc_version = "0.8.23"
evm_version = "cancun"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
